// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: first.proto

package firstJava.services;

public interface firstStructOrBuilder extends
    // @@protoc_insertion_point(interface_extends:firstJava.firstStruct)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();
}
